name: Deployment

on:
  push:
    branches: [deploy]

jobs:

  build:
    runs-on: ubuntu-latest

    steps:
      - name: Install Node
        uses: actions/setup-node@v3
        with:
          node-version: 16

      - name: Checkout code
        uses: actions/checkout@v2

      - name: Install deps
        run: npm ci

      - name: Build
        run: npm run build

      - name: Upload build result
        uses: actions/upload-artifact@v4
        with:
          name: build
          path: ./build

  deploy:
    runs-on: ubuntu-latest
    needs: build
    steps:
      - name: Download build
        uses: actions/download-artifact@v4
        with:
          name: build
      - name: Transfer build files to server
        uses: appleboy/scp-action@master
        with:
          host: 212.111.86.198
          username: ubuntu
          key: ${{ secrets.PRIVATE_KEY }}
          source: "build/*"
          target: "/home/ubuntu/frontend"
          strip_components: 1